# Generated by Django 4.0.5 on 2022-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
